package com.sys.dict.entity;

import com.eshop.frame.base.entity.BaseEntity;

/**
 * Created by tian on 2017/8/4.
 */
public class DictGroupEntity extends BaseEntity {
    private static final long serialVersionUID = -7998490896610191822L;


    private String id;

    /**
     * 字典类型 1 自有字典 2 本系统扩展字典 3 其他系统字典
     *
     * @mbggenerated
     */
    private Short dictType;

    /**
     * 是否缓存
     *
     * @mbggenerated
     */
    private Byte isCache;

    /**
     * 类型组编码
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * 类型组名称
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * 1 树形 2 字符列表 3 数字列表 4 位列表
     *
     * @mbggenerated
     */
    private Short groupType;

    /**
     * 树形: [2%2%2], 定义每级的长度 ;  字符列表: 1 编码长度 前置补0  2 null|0 任意输入
     *
     * @mbggenerated
     */
    private String rule;

    /**
     * 父组编码
     *
     * @mbggenerated
     */
    private String pGroupCode;

    /**
     * 表名
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * 接口名
     *
     * @mbggenerated
     */
    private String interfaceName;

    /**
     * 编码字段
     *
     * @mbggenerated
     */
    private String codeColumn;

    /**
     * 名称字段
     *
     * @mbggenerated
     */
    private String nameColumn;

    /**
     * 扩展字段
     *
     * @mbggenerated
     */
    private String extColumns;

    /**
     * 过滤条件
     *
     * @mbggenerated
     */
    private String filterCond;

    /**
     * 排序语句
     *
     * @mbggenerated
     */
    private String orderClause;

    /**
     * 1 是 0 否
     *
     * @mbggenerated
     */
    private Byte isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.id
     *
     * @return the value of t_d_dict_group.id
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.id
     *
     * @param id the value for t_d_dict_group.id
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.dict_type
     *
     * @return the value of t_d_dict_group.dict_type
     * @mbggenerated
     */
    public Short getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.dict_type
     *
     * @param dictType the value for t_d_dict_group.dict_type
     * @mbggenerated
     */
    public void setDictType(Short dictType) {
        this.dictType = dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.is_cache
     *
     * @return the value of t_d_dict_group.is_cache
     * @mbggenerated
     */
    public Byte getIsCache() {
        return isCache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.is_cache
     *
     * @param isCache the value for t_d_dict_group.is_cache
     * @mbggenerated
     */
    public void setIsCache(Byte isCache) {
        this.isCache = isCache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.group_code
     *
     * @return the value of t_d_dict_group.group_code
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.group_code
     *
     * @param groupCode the value for t_d_dict_group.group_code
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.group_name
     *
     * @return the value of t_d_dict_group.group_name
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.group_name
     *
     * @param groupName the value for t_d_dict_group.group_name
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.group_type
     *
     * @return the value of t_d_dict_group.group_type
     * @mbggenerated
     */
    public Short getGroupType() {
        return groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.group_type
     *
     * @param groupType the value for t_d_dict_group.group_type
     * @mbggenerated
     */
    public void setGroupType(Short groupType) {
        this.groupType = groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.rule
     *
     * @return the value of t_d_dict_group.rule
     * @mbggenerated
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.rule
     *
     * @param rule the value for t_d_dict_group.rule
     * @mbggenerated
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.p_group_code
     *
     * @return the value of t_d_dict_group.p_group_code
     * @mbggenerated
     */
    public String getpGroupCode() {
        return pGroupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.p_group_code
     *
     * @param pGroupCode the value for t_d_dict_group.p_group_code
     * @mbggenerated
     */
    public void setpGroupCode(String pGroupCode) {
        this.pGroupCode = pGroupCode == null ? null : pGroupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.table_name
     *
     * @return the value of t_d_dict_group.table_name
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.table_name
     *
     * @param tableName the value for t_d_dict_group.table_name
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.interface_name
     *
     * @return the value of t_d_dict_group.interface_name
     * @mbggenerated
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.interface_name
     *
     * @param interfaceName the value for t_d_dict_group.interface_name
     * @mbggenerated
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.code_column
     *
     * @return the value of t_d_dict_group.code_column
     * @mbggenerated
     */
    public String getCodeColumn() {
        return codeColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.code_column
     *
     * @param codeColumn the value for t_d_dict_group.code_column
     * @mbggenerated
     */
    public void setCodeColumn(String codeColumn) {
        this.codeColumn = codeColumn == null ? null : codeColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.name_column
     *
     * @return the value of t_d_dict_group.name_column
     * @mbggenerated
     */
    public String getNameColumn() {
        return nameColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.name_column
     *
     * @param nameColumn the value for t_d_dict_group.name_column
     * @mbggenerated
     */
    public void setNameColumn(String nameColumn) {
        this.nameColumn = nameColumn == null ? null : nameColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.ext_columns
     *
     * @return the value of t_d_dict_group.ext_columns
     * @mbggenerated
     */
    public String getExtColumns() {
        return extColumns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.ext_columns
     *
     * @param extColumns the value for t_d_dict_group.ext_columns
     * @mbggenerated
     */
    public void setExtColumns(String extColumns) {
        this.extColumns = extColumns == null ? null : extColumns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.filter_cond
     *
     * @return the value of t_d_dict_group.filter_cond
     * @mbggenerated
     */
    public String getFilterCond() {
        return filterCond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.filter_cond
     *
     * @param filterCond the value for t_d_dict_group.filter_cond
     * @mbggenerated
     */
    public void setFilterCond(String filterCond) {
        this.filterCond = filterCond == null ? null : filterCond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.order_clause
     *
     * @return the value of t_d_dict_group.order_clause
     * @mbggenerated
     */
    public String getOrderClause() {
        return orderClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.order_clause
     *
     * @param orderClause the value for t_d_dict_group.order_clause
     * @mbggenerated
     */
    public void setOrderClause(String orderClause) {
        this.orderClause = orderClause == null ? null : orderClause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_group.is_del
     *
     * @return the value of t_d_dict_group.is_del
     * @mbggenerated
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_group.is_del
     *
     * @param isDel the value for t_d_dict_group.is_del
     * @mbggenerated
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

}
