package com.sys.dict.entity;

import com.eshop.frame.base.entity.BaseEntity;

/**
 * Created by tian on 2017/8/4.
 */
public class DictTypeEntity extends BaseEntity {
    private static final long serialVersionUID = -4904452657451901996L;


    private String id;

    private String pCode;

    /**
     * 编码
     *
     * @mbggenerated
     */
    private String code;

    /**
     * 名称
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 拼音
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * 简拼
     *
     * @mbggenerated
     */
    private String shortPinyin;

    /**
     * 级别，针对树形编码
     *
     * @mbggenerated
     */
    private Short lev;

    /**
     * 排序号
     *
     * @mbggenerated
     */
    private Short sortNo;

    /**
     * 附属标识
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * 类型组编码
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * 1 是 0 否
     *
     * @mbggenerated
     */
    private Byte isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.id
     *
     * @return the value of t_d_dict_type.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.id
     *
     * @param id the value for t_d_dict_type.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.p_id
     *
     * @return the value of t_d_dict_type.p_id
     *
     * @mbggenerated
     */
    public String getPCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.p_id
     *
     * @param pCode the value for t_d_dict_type.p_id
     *
     * @mbggenerated
     */
    public void setPCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.code
     *
     * @return the value of t_d_dict_type.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.code
     *
     * @param code the value for t_d_dict_type.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.name
     *
     * @return the value of t_d_dict_type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.name
     *
     * @param name the value for t_d_dict_type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.pinyin
     *
     * @return the value of t_d_dict_type.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.pinyin
     *
     * @param pinyin the value for t_d_dict_type.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.short_pinyin
     *
     * @return the value of t_d_dict_type.short_pinyin
     *
     * @mbggenerated
     */
    public String getShortPinyin() {
        return shortPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.short_pinyin
     *
     * @param shortPinyin the value for t_d_dict_type.short_pinyin
     *
     * @mbggenerated
     */
    public void setShortPinyin(String shortPinyin) {
        this.shortPinyin = shortPinyin == null ? null : shortPinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.level
     *
     * @return the value of t_d_dict_type.level
     *
     * @mbggenerated
     */
    public Short getLev() {
        return lev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.level
     *
     * @param lev the value for t_d_dict_type.level
     *
     * @mbggenerated
     */
    public void setLev(Short lev) {
        this.lev = lev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.sort_no
     *
     * @return the value of t_d_dict_type.sort_no
     *
     * @mbggenerated
     */
    public Short getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.sort_no
     *
     * @param sortNo the value for t_d_dict_type.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Short sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.flag
     *
     * @return the value of t_d_dict_type.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.flag
     *
     * @param flag the value for t_d_dict_type.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.group_code
     *
     * @return the value of t_d_dict_type.group_code
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.group_code
     *
     * @param groupCode the value for t_d_dict_type.group_code
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_d_dict_type.is_del
     *
     * @return the value of t_d_dict_type.is_del
     *
     * @mbggenerated
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_d_dict_type.is_del
     *
     * @param isDel the value for t_d_dict_type.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

}
