package com.sys.dict.dao;

import com.eshop.frame.base.dao.BaseMapper;
import com.sys.dict.entity.DictGroupEntity;

import java.util.List;

/**
 * Created by tian on 2017/8/4.
 */
public interface DictGroupMapper extends BaseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_group
     *
     * @mbggenerated
     */
    int insert(DictGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_group
     *
     * @mbggenerated
     */
    DictGroupEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_group
     *
     * @mbggenerated
     */
    List<DictGroupEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictGroupEntity record);

    /**
     * 根据groupcode得到值
     *
     * @param groupCode
     * @return
     */
    DictGroupEntity selectByGroupCode(String groupCode);

}
