package com.sys.dict.dao;

import com.eshop.frame.base.dao.BaseMapper;
import com.sys.dict.entity.DictTypeEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * Created by tian on 2017/8/4.
 */
public interface DictTypeMapper extends BaseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_type
     *
     * @mbggenerated
     */
    int insert(DictTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_type
     *
     * @mbggenerated
     */
    DictTypeEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_type
     *
     * @mbggenerated
     */
    List<DictTypeEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_dict_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictTypeEntity record);

    DictTypeEntity selectByCode(@Param("group_code") String groupCode, @Param("code") String code);

    List<DictTypeEntity> selectByGroup(String groupCode);

    List<Map<String, String>> selectListBySQL(@Param("sql") String sql);

    Map<String, String> selectOneBySQL(@Param("sql") String sql);

}
